name: Node.js Package

on:
  push:
    branches:
    - release
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm release
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
