name: NPM Deprecate Old Version Package

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Deprecate Previous Version
        run: npm run deprecates
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
