name: GitHub Pages

on:
  workflow_run:
    workflows: [ Build ]
    types: [requested]
    branches: [main]
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  on-failure-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

  on-success-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - run: echo 'The triggering workflow passed'

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Ready To Publish
        run: npm run release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
